/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        app: {
          bgPrimary: "hsl(var(--color-bg-primary) / <alpha-value>)",
          bgSecondary: "hsl(var(--color-bg-secondary) / <alpha-value>)",
          surface: "hsl(var(--color-surface) / <alpha-value>)",
          border: "hsl(var(--color-border) / <alpha-value>)",
          textPrimary: "hsl(var(--color-text-primary) / <alpha-value>)",
          textSecondary: "hsl(var(--color-text-secondary) / <alpha-value>)",
          textMuted: "hsl(var(--color-text-muted) / <alpha-value>)",
          accentPurple: "hsl(var(--color-accent-purple) / <alpha-value>)",
          accentBlue: "hsl(var(--color-accent-blue) / <alpha-value>)",
          accentCyan: "hsl(var(--color-accent-cyan) / <alpha-value>)",
          accentOrange: "hsl(var(--color-accent-orange) / <alpha-value>)",
          accentPink: "hsl(var(--color-accent-pink) / <alpha-value>)",
          danger: "hsl(var(--color-danger) / <alpha-value>)",
          success: "hsl(var(--color-success) / <alpha-value>)",
          loginBgStart: "hsl(var(--app-login-bg-start) / <alpha-value>)",
          loginBgEnd: "hsl(var(--app-login-bg-end) / <alpha-value>)",
          signupBgStart: "hsl(var(--app-signup-bg-start) / <alpha-value>)",
          signupBgEnd: "hsl(var(--app-signup-bg-end) / <alpha-value>)",
          card: "hsl(var(--color-bg-secondary) / <alpha-value>)",
          cardSoft: "hsl(var(--app-card-soft) / <alpha-value>)",
          borderLegacy: "hsl(var(--app-border) / <alpha-value>)",
          textPrimaryLegacy: "hsl(var(--app-text-primary) / <alpha-value>)",
          textSecondaryLegacy: "hsl(var(--app-text-secondary) / <alpha-value>)",
          primary: "hsl(var(--app-primary) / <alpha-value>)",
          primaryStrong: "hsl(var(--app-primary-strong) / <alpha-value>)",
          accent: "hsl(var(--app-accent) / <alpha-value>)",
          successLegacy: "hsl(var(--app-success) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
